/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'P4_Socket_Pro' 
 * Target:  'P4_Socket_Pro' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Compiler&ARM Compiler:Event Recorder&DAP@1.5.1 */
#define RTE_Compiler_EventRecorder
#define RTE_Compiler_EventRecorder_DAP
/* Keil::Compiler&ARM Compiler:I/O:STDOUT&EVR@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_EVR      /* Compiler I/O: STDOUT EVR */


#endif /* RTE_COMPONENTS_H */
